/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as ApiPublicSetupAdminAdvaxenRouteImport } from './routes/api/public/setup-admin-advaxen'
import { Route as ApiPublicTrackVisitRouteImport } from './routes/api/public/track-visit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminAdvaxenRoute =
  ApiPublicSetupAdminAdvaxenRouteImport.update({
    id: '/api/public/setup-admin-advaxen',
    path: '/api/public/setup-admin-advaxen',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackVisitRoute = ApiPublicTrackVisitRouteImport.update({
  id: '/api/public/track-visit',
  path: '/api/public/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/team': typeof TeamRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/setup-admin-advaxen': typeof ApiPublicSetupAdminAdvaxenRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/team': typeof TeamRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/setup-admin-advaxen': typeof ApiPublicSetupAdminAdvaxenRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/team': typeof TeamRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/team': typeof AdminTeamRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/api/public/setup-admin-advaxen': typeof ApiPublicSetupAdminAdvaxenRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/news'
    | '/projects'
    | '/team'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/projects'
    | '/admin/team'
    | '/news/$slug'
    | '/programs/$slug'
    | '/api/public/setup-admin'
    | '/api/public/setup-admin-advaxen'
    | '/api/public/track-visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/news'
    | '/projects'
    | '/team'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/projects'
    | '/admin/team'
    | '/news/$slug'
    | '/programs/$slug'
    | '/api/public/setup-admin'
    | '/api/public/setup-admin-advaxen'
    | '/api/public/track-visit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/news'
    | '/projects'
    | '/team'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/hero'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/projects'
    | '/admin/team'
    | '/news/$slug'
    | '/programs/$slug'
    | '/api/public/setup-admin'
    | '/api/public/setup-admin-advaxen'
    | '/api/public/track-visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  TeamRoute: typeof TeamRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  ApiPublicSetupAdminAdvaxenRoute: typeof ApiPublicSetupAdminAdvaxenRoute
  ApiPublicTrackVisitRoute: typeof ApiPublicTrackVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admin-advaxen': {
      id: '/api/public/setup-admin-advaxen'
      path: '/api/public/setup-admin-advaxen'
      fullPath: '/api/public/setup-admin-advaxen'
      preLoaderRoute: typeof ApiPublicSetupAdminAdvaxenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-visit': {
      id: '/api/public/track-visit'
      path: '/api/public/track-visit'
      fullPath: '/api/public/track-visit'
      preLoaderRoute: typeof ApiPublicTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTeamRoute: typeof AdminTeamRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTeamRoute: AdminTeamRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  TeamRoute: TeamRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  ApiPublicSetupAdminAdvaxenRoute: ApiPublicSetupAdminAdvaxenRoute,
  ApiPublicTrackVisitRoute: ApiPublicTrackVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
